name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check file structure
      run: |
        # Check that required directories exist
        if [ ! -d "models" ]; then echo "Missing models directory"; exit 1; fi
        if [ ! -d "Processed_Data" ]; then echo "Missing Processed_Data directory"; exit 1; fi
        # Check that key files exist
        if [ ! -f "app.py" ]; then echo "Missing app.py"; exit 1; fi
        if [ ! -f "requirements.txt" ]; then echo "Missing requirements.txt"; exit 1; fi
    
    - name: Setup dummy model for testing
      run: |
        # Create a minimal structure for testing without actual data
        mkdir -p models/smote
        mkdir -p Processed_Data
        
        # Create a simple feature names file
        mkdir -p models
        echo '["feature1", "feature2", "feature3"]' > models/feature_names.json
        
        # Create a dummy CSV for testing
        echo "Meeting_Date,CPI_Inflation_mean,GDP_Growth_mean,Unemployment_Rate_mean,slope_10y_2y_mean,EUR_USD_mean,Fed_Fund_Rate_mean,Brent_Oil_Price_mean,Interval_Start,Interval_End,Next_Rate_Change" > Processed_Data/ecb_meeting_data.csv
        echo "2023-01-01,2.5,1.5,7.0,0.5,1.1,4.0,80,2022-12-01,2023-01-31,0" >> Processed_Data/ecb_meeting_data.csv
    
    - name: Test Streamlit app structure
      run: |
        # Check that the Streamlit app can be imported without errors
        python -c "import streamlit; import app" 