[theme]
primaryColor = "#1a5276"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#343a40"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = true
runOnSave = true

[browser]
gatherUsageStats = false

[global]
developmentMode = false 